# Generated by Django 4.0.3 on 2022-04-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dailycaloriecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycaloriecount',
            name='date',
            field=models.CharField(max_length=122),
        ),
    ]
