# Generated by Django 4.0.3 on 2022-04-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCaloriesBurnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('burntCalories', models.IntegerField()),
                ('date', models.CharField(max_length=122)),
            ],
        ),
    ]
